### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by ergonomicus** [fico7489/laravel-eloquent-join#1]
I have followed the instructions on how to install this package, but I get "Invalid argument supplied for foreach()" error in validateJoinQuery($relatedModel) method call. Any idea?

**Comment by fico7489** [comment]
@ergonomicus  can you paste your relation in models on which you are performing queries, table names of models, and query code?

**Comment by ergonomicus** [comment]
@fico7489 I can paste only parts of code, it's an internal app...

Here are my models

```
// Event model
use Illuminate\Database\Eloquent\Model;
use App\Models\Work;
use Fico7489\Laravel\EloquentJoin\Traits\EloquentJoinTrait;

class Event extends Model
{
    // table 'events'
    use EloquentJoinTrait;

    public function work()
    {
        return $this->belongsTo(Work::class);
    }

    // bunch of other relations and accessors...
}

// Work model
use Illuminate\Database\Eloquent\Model;
use App\Models\Event;

class Work extends Model
{
    // table 'works'

    public function events()
    {
        return $this->hasMany(Event::class);
    }

    // bunch of other relations and accessors...
}
```
Here is my controller method
```
    public function index()
    {
        // works table has a boolean field 'is_archived' and datetime field 'start'
        $events = Event::with('eventStatus', 'work.customer.address')->orderByJoin('work.is_archived')->orderBy('start')->get();
        
        return view('events.index', compact('events'));
    }
```
Laravel 5.5.latest and PHP 7.1.12

Thanks.

**Comment by fico7489** [comment]
both models should use EloquentJoinTrait so you need to user EloquentJoinTrait in Work model also, but a better solution would be to create BaseModel model which extends Model, use EloquentJoinTrait in BaseModel and then both models can extend BaseModel, not Model.

PS. I will update the docs so this will be more clear...

**Comment by ergonomicus** [comment]
@fico7489 Ok, thank you. I will try again...
