### ISSUE TITLE
SQL 1066: Not unique table/alias (when repeating relation)

### ISSUE THREAD

**Issue by mykeels** [fico7489/laravel-eloquent-join#10]
### Description

A table `users` is mapped to `providers` with a `hasOne` relationship, which is then mapped to `users` again with a `belongsTo` relationship.

### Steps to Reproduce

When I execute `orderByJoin('providers.users.name', $type)`, I get the error 

```
SQL 1066: Not unique table/alias
```

### What I think

This is because the `users` table is repeated in the mapping, so it needs unique aliases for each instance.

### Generated SQL

```sql
select count(*) as aggregate from `users` left join `providers` on `providers`.`user_id` = `users`.`id` and `providers`.`deleted_at` is null left join `users` on `users`.`id` = `providers`.`user_id` and `users`.`deleted_at` is null where exists (select * from `lv_roles` inner join `practice_role_user` on `lv_roles`.`id` = `practice_role_user`.`role_id` where `users`.`id` = `practice_role_user`.`user_id` and `name` = participant) and exists (select * from `user_info` where `users`.`id` = `user_info`.`user_id` and `user_info`.`deleted_at` is null) and `users`.`deleted_at` is null group by `users`.`id`)
```

**Comment by mykeels** [comment]
I found that in my BaseModel where I inherited from the `EloquentJoinTrait`, I could override the value of `$useTableAlias` in the constructor:

```php
class BaseModel extends Model
{
    use EloquentJoinTrait;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->useTableAlias = true;
    }
}
```

which fixed the issue

**Comment by fico7489** [comment]
you are right, docs will be updated...

**Comment by fico7489** [comment]
updated here : https://github.com/fico7489/laravel-eloquent-join/commit/bdd6b90d508e11043abd7c9039c999cad76946bd
