### ISSUE TITLE
wrong attribute value

### ISSUE THREAD

**Issue by abilogos** [fico7489/laravel-eloquent-join#102]
Hi, i have  encountered an issue in case of using Not explicitly:
this line of code works fine:

    $goods = Good::select("goods.*")->join("products","products.id","goods.product_id")->
 but this line of code:

    $goods = Good::select("*")->join("products","products.id","goods.product_id")->
or this:

    $goods = Good::join("products","products.id","goods.product_id")->

makes problem with i am trying to access one of the models id:

    $good->id;  //it retrieves product.is instead of good.id

**Comment by fico7489** [comment]
but if you are selecting everything 

`Good::select("*")
`
it is a expected behaviour.

**Comment by abilogos** [comment]
But The below line get me products.id instead of goods.id
    $goods = Good::select("*")->join("products","products.id","goods.product_id")->

**Comment by fico7489** [comment]
That is expected behaviour, because now you have two fields with the same name "id" (from goods and products) in select and last id from select is fetched into results. This issue is related to the mysql, not this package...
