### ISSUE TITLE
Join multiple relationships by calling the joinRelations method once

### ISSUE THREAD

**Issue by freekup** [fico7489/laravel-eloquent-join#103]
I have a problem when I want to combine multiple relationships by calling the joinRelations method once. In this case, I have three tables. Users, UserAvatar, and Products. If I want to combine all my tables with the help of this repository, I need to write this code:

```php
User::query()->joinRelations('userAvatar')->joinRelations('product');
```

But, can I make this code simpler like this?

```php
User::query()->joinRelations(['userAvatar', 'product']);
```

I think it is a good idea if you can add this feature.

**Comment by fico7489** [comment]
you are right, I will add it ...

**Comment by freekup** [comment]
I recently fork your repository and added a method like this.

```php
    public function joinMultipleRelations(array $relations)
    {
        foreach($relations as $relation) {
            $this->joinRelations($relation);
        }
        return $this;
    }
```
<br/>
I added a new method because, in my opinion it will not break the old users of this repository. What do you think?

**Comment by fico7489** [comment]
I think it is best to use same function : 

	
```
public function joinRelations($mixed)
{
	if(is_array(mixed)){
		foreach($relations as $relation) {
			$this->joinRelations($relation);
		}
	}else{
		//...
	}
	
	return $this;
}
```

many of laravel functions work that way...

**Comment by freekup** [comment]
What if many users use the second parameter of the method? I think It will break the user's project
