### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by kennyturner** [fico7489/laravel-eloquent-join#119]
Have forked and updated to Laravel 9. Not many changes.
However the tests will not complete and now seem to be outdated.
Not sure if this package is still supported or if i should look for another solution.

Thanks

**Comment by mikebronner** [comment]
I just submitted PR #120 that fixes the tests and updates the code accordingly.

**Comment by kennyturner** [comment]
Thanks for giving it a try, i had the same issues with the tests not working.
I changed the workflow locally and ll good but failed on github also.
Hopefully will be fixed soon, as I like the package and saves alot of work.
Hopefully will maintained for a bit longer.

**Comment by fico7489** [comment]
done!
