### ISSUE TITLE
Problems with GroupBy in simple orderByJoin

### ISSUE THREAD

**Issue by alvarollmenezes** [fico7489/laravel-eloquent-join#12]
Hi, thank you for the package, it seems pretty useful.

I'm getting an error caused by the group by from https://github.com/fico7489/laravel-eloquent-join/blob/master/src/Traits/EloquentJoinTrait.php#L145.

For example, It creates a query like:
`"select "orders".* from "orders" left join "statuses" on "statuses"."id" = "orders"."statusId" where "orders"."deleted_at" is null group by "orders"."id" order by "statuses"."name" asc"`

Which gives me this error in postgresql:
column \"statuses.name\" must appear in the GROUP BY clause or be used in an aggregate function

I wonder why is this group by there and if I'm doing something wrong, as it seems a very trivial usage of the package.

I'm using the query like:
`Order::orderByJoin('status.name');`

Thank you.

**Comment by fico7489** [comment]
@alvarollmenezes  I run all tests on mysql and everything seems to work fine for mysql, anyway, I am planing to remove groups by from the next package release.

**Comment by alvarollmenezes** [comment]
Good to know, I'll be waiting for the release. For the mean time I'll be using my fork.

**Comment by alexleonard** [comment]
@fico7489 I've just encountered this same error - is the groups by removal happening soon?

**Comment by alexleonard** [comment]
I've also created a fork and am using that for the moment, so no rush :)

And thanks so much for this package, it solved a particularly painful issue for me :+1:
