### ISSUE TITLE
Mutliple orWhereJoins

### ISSUE THREAD

**Issue by fish-4-fun** [fico7489/laravel-eloquent-join#13]
In Eloquent, we can do something like this 

```
$builder->where(function ($query) use ($value) {
           $query->where('profile.first_name', 'LIKE', "%{$value}%");
           $query->orWhere('profile.last_name', 'LIKE', "%{$value}%");
           $query->orWhere('profile.address', 'LIKE', "%{$value}%");
});
```

Since this library doesn't allow closures, I don't know if this is possible. I can change the above to:

```
$builder->where(function ($query) use ($value) {
           $query->whereJoin('profile.first_name', 'LIKE', "%{$value}%");
           $query->orWhereJoin('profile.last_name', 'LIKE', "%{$value}%");
           $query->orWhereJoin('profile.address', 'LIKE', "%{$value}%");
});
```

Two issues arise:

1. The join of the profile table is not included when WhereJoin or OrWhereJoin is used inside this closure.

2. The parenthesis are not in the correct positions. It seems as though you can only use 2 columns in such a request. If the above code is pulled out of the closure, the parenthesis are still wrong. It produces 

```
where ((`user_profiles`.`first_name` LIKE ? or (`user_profiles`.`last_name` LIKE ?)) or (`user_profiles`.`last_name` LIKE ?))
```

Is there currently a way to properly do an OrWhereJoin with more than 2 columns in question?

**Comment by fico7489** [comment]
thanks for the feedback,I understand what is the problem, I will check this in next this in next package version...

**Comment by fish-4-fun** [comment]
Do you mind just explaining where you think the issue maybe (if you're aware) or point me to a place to start looking as I will try and fix it and do a pull request. I am in the process of trying to understand the code but some of it is still a little bit magical at the moment. Thanks!

**Comment by fico7489** [comment]
I should adjust package a lot to support closures, so there is no simple answer on your question...

**Comment by fish-4-fun** [comment]
No worries, I've ended up checking for an array in 
```
scopeOrWhereJoin
``` 
and if so I iterate though and attempt all the joins (as before) and just perform the native eloquent orWhere closure. So defining it would look something like this:

```
 $builder->orWhereJoin(['profile.first_name','profile.last_name'], 'LIKE', "%filter%");
```

and in scopeOrWhereJoin
```
//check for array
 return $builder->where(function ($query) use ($value, $tables, $operator, $builder) {
                foreach ($tables as $table) {
                    $column = $this->performJoin($builder, $table);
                    $query->orWhere($column, $operator, $value);
                }
            });

else
//proceed as before...

```

So far I don't think I've introduced any side affects, though, you are correct, a more robust solution would be the better option. Because of this I won't submit a PR, but this currently satisfies all my requirements going forward.

**Comment by fico7489** [comment]
@fish-4-fun  see this one https://github.com/laravel/framework/issues/24996


I don't think this is normal behaviour from laravel, what do you think ?
