### ISSUE TITLE
[Question] Use of left join instead of inner join

### ISSUE THREAD

**Issue by dariusj18** [fico7489/laravel-eloquent-join#16]
Is there any reason EloquentJoinTrait's performJoin method uses left joins instead of inner joins?

In my uses I cannot see a reason to use left joins, especially if you are filtering based on things in the foreign table.

**Comment by fico7489** [comment]
there is no special reason, in some cases **left joins** fits better in other  **inner joins** fits better. In future plugin releases I will add better control for that...

**Comment by fico7489** [comment]
here you can follow progress of new version 
https://github.com/fico7489/laravel-eloquent-join/compare/new?expand=1

it will be published soon...
