### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::setInvalidJoin()

### ISSUE THREAD

**Issue by ThiruKandy** [fico7489/laravel-eloquent-join#2]
I'm getting this error when loading relations.
$comment->load(['post', 'owner'])
only on Post model, I have used EloquentJoinTrait, not in Owner model. If I load only post I not getting the error, only for the owner I'm getting this error. any idea?

**Comment by fico7489** [comment]
@ThiruKandy you must use EloquentJoinTrait in both models Post and Owner. It would be best to use it in the base model.

**Comment by ThiruKandy** [comment]
@fico7489 for an existing system we can't implement it to all models, can't we set it for only models that use orderByJoin?

**Comment by fico7489** [comment]
@ThiruKandy yes, you can set it for only models that use orderByJoin, it will work...

**Comment by ThiruKandy** [comment]
In this example, I have used EloquentJoinTrait in Comment and Post models, not in Owner model. 
$comment->load(['post', 'owner'])
I'm getting this error "setInvalidJoin()". But if I load only Post I don't get any error.

**Comment by ThiruKandy** [comment]
@fico7489 And if I use EloquentJoinTrait on both models then there is no error. any idea?

**Comment by fico7489** [comment]
If you want to use orderByJoin for both Post and Owner relations then you need use trait in all 3 models: Post, Owner, and Comment, if you want to sort only posts then you need trait in Post and Comment...

**Comment by ThiruKandy** [comment]
Thank You. Yes, I only want to sort posts, so I have added trait in Post and Comment, the orderByJoin workes fine.

**BUT** when I load a un-trait relation, then I'm getting this error 'Call to undefined method Illuminate\Database\Query\Builder::setInvalidJoin()'.

**Comment by ThiruKandy** [comment]
@fico7489 I'm using the suggested way "base model".

**Comment by ThiruKandy** [comment]
@fico7489 In Owner model I have not used the Trait, but used in Comment. If I load 'Owner' on Comment `($comments->load('owner'))`, than I'm getting this error setInvalidJoin.

**Comment by fico7489** [comment]
@ThiruKandy  can you paste how you relations look like?

**Comment by ThiruKandy** [comment]
**Base model**
```
use Illuminate\Database\Eloquent\Model;
use Fico7489\Laravel\EloquentJoin\Traits\EloquentJoinTrait;
class BaseModel extends Model
{
    use EloquentJoinTrait;
}
```

**Post model**
```
use App\BaseModel;
class Post extends BaseModel
{
	public function comments()
	{
        return $this->hasMany(Comment::class);
    }

        public function owner()
	{
        return $this->belongsTo(Owner::class);
    }
```

**Comment model**
```
use App\BaseModel;
class Comment extends BaseModel
{
	public function post()
	{
        return $this->belongsTo(Post::class);
    }

        public function owner()
	{
        return $this->belongsTo(Owner::class);
    }
```

**Owner model**
```
use Illuminate\Database\Eloquent\Model;
class Owner extends Model
{
	public function posts()
	{
        return $this->hasMany(Post::class);
    }

        public function comments()
	{
        return $this->hasMany(Comment::class);
    }

```

**Comment controller**
```
class CommentController extends Controller
{
	public function show(Comment $comment)
    {
        $comment->load('post', 'owner');

```

![error](https://user-images.githubusercontent.com/35560159/35096412-00b080fe-fc44-11e7-8d30-8fed81e83e32.png)

**Comment by fico7489** [comment]
@ThiruKandy  which laravel version?

**Comment by ThiruKandy** [comment]
@fico7489 "laravel/framework": "^5.4.0"

**Comment by fico7489** [comment]
@ThiruKandy  this is just composer.json defined version, this means that it could be some version between 5.4.0 and 5.4.36. Can you find an exact version in composer.lock?

**Comment by ThiruKandy** [comment]
Laravel Framework 5.4.36

**Comment by ThiruKandy** [comment]
@fico7489 do I need to update this version?

**Comment by fico7489** [comment]
No,  5.4.36 is the newest laravel 5.4.* version. 

Your models look fine and it should be working.
I am willing to help you if you want to send me repo with the problem or create test repo where this problem exists...

For me everything works fine for 5.4.36 version, also it is covered by tests...

**Comment by fico7489** [comment]
@ThiruKandy  I think I detected a problem, I think that problem is that scopes are not initialized when eloquent is used outside laravel https://laravel.com/docs/5.4/eloquent#query-scopes

**Comment by fico7489** [comment]
@ThiruKandy  can you try with the updated package? you can update package with : 
"composer update fico7489/laravel-eloquent-join"
