### ISSUE TITLE
Next version input

### ISSUE THREAD

**Issue by dariusj18** [fico7489/laravel-eloquent-join#21]
I have been working on similar things as you for this package over the last several months.

https://github.com/dariusj18/laravel-eloquent-join/commits/master

I would like to present some differences in where you have gone vs where I did.

1. I tried to do more Laravelish way of using method names to change what type of Join to use.  Doing this allows for cross joins as well (I don't use them much, but Laravel has specific cross join methods as well).  However there is definitely the issue of reverse compatibility.
2. I added the `BelongsToManyJoin` relation, I may have been naive, however it worked for my purposes.
3. I added `orderByJoinPivot`, this is a natural extension of the `BelongsToManyJoin` and is very useful.
4. I see you also removed the `groupBy`, however I don't think there should be the extra select added automatically either.  If anything, I think it would be best to have an additional method to let the user choose to add the grouping if they think it is needed.
5. I switch the `ExtendRelationsTrait` to override the `newBelongsTo` and `newHasOne` methods that Laravel added in 5.5 https://github.com/laravel/framework/pull/22617

I would appreciate any feedback on my suggestions.

**Comment by fico7489** [comment]
1.yes 3.* is not backward compatible, because of this I named it 3.* not 2.*
I don't want to supports < 5.5 anymore
By my opinion I think that is better to pass join type in parameter rather that use 3 different methods

2.I have in plan also to support HasMany relation, method for join should be something like this 

    public function orderByJoin($column, $sortBy = 'asc|desc', $joinType = 'left|inner|cross', $sortTypeJoin = 'id', $sortByJoin = 'asc')

3.orderByJoinPivot can be usefull also, but this method is for pivot table on HasMany relation

4.group by is not needed anymore because I added this https://github.com/fico7489/laravel-eloquent-join/blob/master/src/EloquentJoinBuilder.php#L101
maybe I can allow user from choose between this new way or group by

5.Extending laravel relations are awkward, acctually I requested that improvement : 

https://github.com/laravel/framework/pull/22382

😄

**Comment by dariusj18** [comment]
1. Yeah, I prefer it that way too, but using the method name is more Laravely.

4. The issue I see with either method is it's kind of an unexpected behavior.  It also doesn't give you the option to determine which records to get, with your subquery there is no ordering, so there is nothing giving the user the ability to determine which is the top record, it leaves that up to the database and how it decides to store records.  This is at it's root is an issue with Eloquent and how it assumes one row per record when hydrating models

5. Excellent, makes sense.

**Comment by fico7489** [comment]
2.hm yeah I really didn't finished concept but it will be something like this : 

order products by first value : 

    Products::orderByJoin('price.units.value', 'asc'', 'left', 'first ')

order products by min value : 

    Products::orderByJoin('price.units.value', 'asc'', 'left', 'min')

order products by max value : 

    Products::orderByJoin('price.units.value', 'asc'', 'left', 'max')

**Comment by fico7489** [comment]
2.hm yeah I really didn't finished concept but it will be roughly something like this : 

order by related table 

    //order products by units name (subquery will get first unit asc by name)
    Products::orderByJoin('units.name', 'asc', 'left', 'name', 'asc')

    //order products by units name (subquery will get last unit asc by name)
    Products::orderByJoin('units.name', 'asc', 'left', 'name', 'desc')

    //order products by units name (subquery will get first unit asc by id)
    Products::orderByJoin('units.name', 'asc', 'left', 'id', 'desc')

    //order products by units name (subquery will get first unit asc by min id)
    Products::orderByJoin('units.name', 'asc', 'left', 'value', 'id', 'min')

order by pivot table 
	
    Products::orderByJoinPivot('units.value', 'asc', 'left', 'value', 'min')
    Products::orderByJoinPivot('units.value', 'asc', 'left', 'value', 'max')
	
tables

    products
    id|name|shop_id

    units
    id|name

    product_unit
    id|product_id|unit_id|value

**Comment by fico7489** [comment]
If you have more questions or suggestion feel free to ask me
