### ISSUE TITLE
How to use another where clause after orWhereJoin()?

### ISSUE THREAD

**Issue by farismohammed** [fico7489/laravel-eloquent-join#22]
in my case where() clause after orWhereJoin() is not working. no changes in results.

**Comment by fico7489** [comment]
orWhereJoin can be combined with where() orWhere(), whereJoin() and orWhereJoin()  as much as you want.


Can you paste how you want your code to look like ?

**Comment by farismohammed** [comment]
My query looks like this..!

`Post::orwhereJoin('name', 'like', '%q%')->orwhereJoin('category.name', 'like', '%q%')->where('id' '!=', 1);`

I want to use where()  clause in last in my query.

**Comment by fico7489** [comment]
which error you get ?

**Comment by farismohammed** [comment]
There is no error. the last where() clause not affecting the query, that's my problem.

**Comment by fico7489** [comment]
can you detect how generated query looks like : 

    \DB::enableQueryLog();
    Post::orwhereJoin('name', 'like', '%q%')->orwhereJoin('category.name', 'like', '%q%')->where('id' '!=', 1);
    print_r(\DB::getQueryLog());exit;

?

**Comment by farismohammed** [comment]
Tested in Role Model

```
\DB::enableQueryLog();
Role::orwhereJoin('name', 'like', '%admin%')->orwhereJoin('category.name', 'like', '%admin%')->where('id' '!=', 1)->where('id', '!=', 2);
print_r(\DB::getQueryLog());exit;
```
Generated query

```
select * from `roles` where `roles`.`name` like '%admin%' or `roles`.`display_name` like '%admin%' and `id` != 1 and `id` != 2
```

**Comment by fico7489** [comment]
User::orWhereJoin('first_name', 'like', '%admin%')->orWhereJoin('first_name', 'like', '%admin%')->where('id', '!=', 1)->where('id', '!=', 2)->get();
    User::orWhere('first_name', 'like', '%admin%')->orWhere('first_name', 'like', '%admin%')->where('id', '!=', 1)->where('id', '!=', 2)->get();

package generates the same query as laravel core : 

	Array
	(
		[0] => Array
			(
				[query] => select * from `users` where (`users`.`first_name` like ? or `users`.`first_name` like ? and `id` != ? and `id` != ?) and `users`.`deleted_at` is null
				[bindings] => Array
					(
						[0] => %admin%
						[1] => %admin%
						[2] => 1
						[3] => 2
					)

				[time] => 82.59
			)

		[1] => Array
			(
				[query] => select * from `users` where (`first_name` like ? or `first_name` like ? and `id` != ? and `id` != ?) and `users`.`deleted_at` is null
				[bindings] => Array
					(
						[0] => %admin%
						[1] => %admin%
						[2] => 1
						[3] => 2
					)

				[time] => 4.85
			)

	)
