### ISSUE TITLE
leftJoin argument only available on orderByJoin.

### ISSUE THREAD

**Issue by dariusj18** [fico7489/laravel-eloquent-join#24]
I still suggest going with the more laravelesque whereJoin, whereLeftJoin, and whereCrossJoin.  However currently it seems on the orderByJoin method has your current change adding the $leftJoin argument.

**Comment by fico7489** [comment]
I think that is better to add $joinType = inner|right|left|cross argument instead $leftJoin = true|false or instead 4 new methods

**Comment by dariusj18** [comment]
That works too
