### ISSUE TITLE
use orWhreJoin inside of query function getting an error.

### ISSUE THREAD

**Issue by shabeerkdm** [fico7489/laravel-eloquent-join#25]
I have a query which is working with orWhere, but if I use orWhereJoin instead of it getting an error

Query - Laravel (orWhere)
```
            DeviceModel::where(function ($query) {
                      $query ->orWhere('device_company_name', '=', 'samsung');
                      $query ->orWhere('device_company_name', '=', 'mi');
            })
            ->where('id', '!=', '1')
            ->get();
```

Query - Laravel-eloquent-join (orWhereJoin)
```
DeviceModel::where(function ($query) {
                      $query ->orWhereJoin('deviceCompany.name', '=', 'samsung');
                      $query ->orWhereJoin('deviceCompany.name', '=', 'mi');
            })
            ->where('id', '!=', '1')
            ->get();
```

**Comment by fico7489** [comment]
1.can you paste error you get? 
2.can you paste your role relation code  in user model ? is it role or roles, because if it is roles then : 

    $query ->orWhereJoin('roles.name', '=', 'user');

**Comment by shabeerkdm** [comment]
> I have a query which is working with orWhere, but if I use orWhereJoin instead of it getting an error
> 
> Query - Laravel (orWhere)
> 
> ```
>             DeviceModel::where(function ($query) {
>                       $query ->orWhere('device_company_name', '=', 'samsung');
>                       $query ->orWhere('device_company_name', '=', 'mi');
>             })
>             ->where('id', '!=', '1')
>             ->get();
> ```
> Query - Laravel-eloquent-join (orWhereJoin)
> 
> ```
> DeviceModel::where(function ($query) {
>                       $query ->orWhereJoin('deviceCompany.name', '=', 'samsung');
>                       $query ->orWhereJoin('deviceCompany.name', '=', 'mi');
>             })
>             ->where('id', '!=', '1')
>             ->get();
> ```


DeviceModel relationship

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Fico7489\Laravel\EloquentJoin\Traits\EloquentJoin;

class DeviceModel extends Model
{
    use SoftDeletes;
    use EloquentJoin;
    //
    protected $dates = ['deleted_at'];

    public function deviceCompany(){
    	return $this->belongsTo('App\DeviceCompany');
    }
}
```
ERROR

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'device_companies.name' in 'where clause' (SQL: select * from device_models where (`device_companies`.`name` = samsung or device_companies.name = mi) and id != 1 and device_models.deleted_at is null)`

**Comment by farismohammed** [comment]
@fico7489 facing the same problem... any solution..???

**Comment by fico7489** [comment]
here is fix for issue https://github.com/fico7489/laravel-eloquent-join/pull/28/files
it will be merged soon

**Comment by fico7489** [comment]
merged

**Comment by farismohammed** [comment]
Thank you .. problem solved.
