### ISSUE TITLE
Collision with Eloquence 

### ISSUE THREAD

**Issue by gabrielleverneuil** [fico7489/laravel-eloquent-join#27]
#When I add the EloquentJoin Trait I have this error :
Trait method newEloquentBuilder has not been applied, because there are collisions with other trait methods.

By removing others traits one by one, I deduced that it came from the Eloquence one, and Indeed, it's the same methods named used.

Do you have any ideas to how I can solved that ? 

Also, I wondering if you have planned in the future to add clauses in BelongsTo and HasOne like with ?

Thanks in advance

**Comment by gabrielleverneuil** [comment]
Thanks for your reply, 
If you do not recommend using both packages together, no need to answer the second one.
You can close this issue.

**Comment by fico7489** [comment]
you are referring to this package : https://github.com/kirkbushell/eloquence ?

**Comment by gabrielleverneuil** [comment]
nop this one : https://github.com/jarektkaczyk/eloquence-base

**Comment by fikrimi23** [comment]
Is this final solution ? can I have workaround ?

**Comment by marnickmenting** [comment]
I encountered the same problem, until I found out the eloquence-base package has it's own join method implemented. For future reference: https://github.com/jarektkaczyk/eloquence/wiki/Builder-searchable-and-more#joining-relations
