### ISSUE TITLE
Foreign key missing in generated Query

### ISSUE THREAD

**Issue by TheFehr** [fico7489/laravel-eloquent-join#3]
This query was generated: 

> select `user`.* from `user` left join `user_type_3` on `user_type_3`.`ut3_id_user` = `user`.`` group by `user`.`u_id` order by `user_type_3`.`ut3_premium` asc limit 50

And this
```
public function teacherinfo()
{
       return $this->hasOne(Teacher::class, 'ut3_id_user');
}
```
and this
```
public function teacherinfo()
{
     return $this->hasOne('User');
}
```
are the used relations and this
```
$users = User::with('subjects', function($query) use ($fach) {
     return $query->where('f_id', $fach->f_id);
})->with('teacherinfo')->orderByJoin('teacherinfo.ut3_premium')->take(50)->get();
```
was the used function call.

I tried to locate the problem and my guess is it has something to do with line 109 in EloquentJoinTrait.php
`$keyRelated = $relatedRelation->getForeignKey();`

Do you have an idea, why this could be happening?
Thanks

**Comment by fico7489** [comment]
@TheFehr  can you  try to change EloquentJoinTrait line 97 from 

            $relatedPrimaryKey = $relatedModel->primaryKey;

to

            $relatedPrimaryKey = $relatedModel->getKeyName();

? If this solves your problem I will commit it...

**Comment by fico7489** [comment]
@TheFehr  which laravel version?

**Comment by TheFehr** [comment]
@fico7489 No Laravel I'm using eloquent without laravel, eloquent is v5.4.36

**Comment by fico7489** [comment]
@TheFehr  oh this may be a problem, can you check what is returned in EloquentJoinTrait at line 117 : 

```
} elseif ($relatedRelation instanceof HasOneJoin) {
    $keyRelated = $relatedRelation->getQualifiedForeignKeyName();
    dd($keyRelated );
```

**Comment by fico7489** [comment]
@TheFehr oh this may be a problem, can you change in EloquentJoinTrait at line 97 from : 

        $relatedPrimaryKey = $relatedModel->primaryKey;
to

        $relatedPrimaryKey = $relatedModel->getKeyName();
? If this solves your problem I will commit it...

**Comment by TheFehr** [comment]
I got it working but with an other change on the same line
I changed it to:
` $relatedPrimaryKey = $currentModel->getKeyName();`
But I think this could lead to problems with the BelongsToJoin query.
And because I'm dealing with quite big tables I figured out that I have to write my own queries for performance improvement.

**Comment by fico7489** [comment]
@TheFehr  do you want to submit PR ?

**Comment by TheFehr** [comment]
Until next week I haven't got time to do some testing. But I would like to do some next week and submit a PR if everything goes smooth.

**Comment by fico7489** [comment]
@TheFehr it looks that the issue exists only if you use eloquent outside laravel. I am closing this one and I am expecting PR from you :D

PS: Join is super fast if you use indexes, much more that subqueries which are used with eloquent whereHas clause...
