### ISSUE TITLE
Need orWhereNotInJoin()....!!

### ISSUE THREAD

**Issue by farismohammed** [fico7489/laravel-eloquent-join#30]
I want's to use like `$user->whereNotInJoin('roles.id', [1, 2, 3, 4, 5, 6, 7, 8])`
thanks

**Comment by fico7489** [comment]
working on it ...

**Comment by fico7489** [comment]
PR for whereIn, whereNotIn, orWhereIn, orWhereNotIn is here : 
https://github.com/fico7489/laravel-eloquent-join/pull/49/files

**Comment by fico7489** [comment]
merged! 4.0.5 version ....
