### ISSUE TITLE
Record is removed when BelongsTo record is null 

### ISSUE THREAD

**Issue by mungpara** [fico7489/laravel-eloquent-join#32]
I have Post model and User model

i have some post where user_id is null

public function user()
{
        return $this->belongsTo('App\User');
}

Post::orderByJoin('user.name');

this only return records where user_id is not null.

how can i solve this. i also want that post where user_id is null

**Comment by fico7489** [comment]
Post::setLeftJoin(true)->orderByJoin('user.name');

**Comment by mungpara** [comment]
thanks
