### ISSUE TITLE
 Integrity constraint violation: 1052 Column 'name' in where clause is ambiguous

### ISSUE THREAD

**Issue by mungpara** [fico7489/laravel-eloquent-join#33]
Post::with('category')
            ->whereHas('category', function ($q) use ($search) {
                if (isset($search) && !empty($search)) {
                    $q->where('name', 'LIKE', '%' . $search . '%');
                }
            })
            ->where(function ($q) use ($search) {
                if (isset($search) && !empty($search)) {
                    $q->where('name', 'LIKE', '%' . $search . '%');
                }
            })
            ->setLeftJoin(false)
            ->orderByJoin('category.name', 'desc')
            ->paginate();

Showing this error

 SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'name' in where clause is ambiguous (SQL: select count(*) as aggregate from `posts` left join `categories` on `categories`.`id` = `posts`.`category_id` where exists (select * from `categories` where `posts`.`category_id` = `categories`.`id` and `name` LIKE %r%) and (`name` LIKE %r%) group by `posts`.`id`)

**Comment by mungpara** [comment]
i also tried with setLeftJoin(false)

**Comment by fico7489** [comment]
can you try change 

    $q->where('name', 'LIKE', '%' . $search . '%');

to

    $q->where('category.name', 'LIKE', '%' . $search . '%');

?

**Comment by mungpara** [comment]
Post::with('category')
->whereHas('category', function ($q) use ($search) {
if (isset($search) && !empty($search)) {
$q->where('name', 'LIKE', '%' . $search . '%');
}
})
->setLeftJoin(false)
->orderByJoin('category.name', 'desc')
->paginate();

this is working perfectly 
i tries category.name its not working

**Comment by mungpara** [comment]
category search working but issue occured in post search

**Comment by mungpara** [comment]
Error in this actually 

Post::with('category')
->where(function ($q) use ($search) {
if (isset($search) && !empty($search)) {
$q->where('name', 'LIKE', '%' . $search . '%');
}
})
->setLeftJoin(true)
->orderByJoin('category.name', 'desc')
->paginate();

**Comment by fico7489** [comment]
this is not tested, but something like this should work and it is more elegant : 

	$query = Post::with('category');

	if (!empty($search)) {
		$query->whereJoin('category.name', 'LIKE', '%' . $search . '%');,
	}
	if (!empty($search)) {
		$query->orWhereJoin('posts.name', 'LIKE', '%' . $search . '%');,
	}

	$posts = $query->setLeftJoin(false)
		->orderByJoin('category.name', 'desc')
		->paginate();

**Comment by mungpara** [comment]
thanks a lot
````
$query = Post::with('category');

if (!empty($search)) {
	$query->whereJoin('category.name', 'LIKE', '%' . $search . '%');
}
if (!empty($search)) {
	$query->orWhereJoin('name', 'LIKE', '%' . $search . '%');
}

$posts = $query->setLeftJoin(false)
	->orderByJoin('category.name', 'desc')
	->paginate();
```

working now 👍
