### ISSUE TITLE
No WhereIn

### ISSUE THREAD

**Issue by victoratsuta** [fico7489/laravel-eloquent-join#39]
No realization of where in. How I can solve this issue? or add this method, please.

**Comment by fico7489** [comment]
more methods like WhereIn and WhereNotIn will be added soon....

**Comment by fico7489** [comment]
PR for whereIn, whereNotIn, orWhereIn, orWhereNotIn is here : 
https://github.com/fico7489/laravel-eloquent-join/pull/49/files

**Comment by fico7489** [comment]
merged! 4.0.5 version ....
