### ISSUE TITLE
Private/public issue within EloquentJoinTrait.php

### ISSUE THREAD

**Issue by ReneBakkerBBIT** [fico7489/laravel-eloquent-join#4]
Great package. However, I had a minor problem.
I had to change the EloquentJoinTrait properties _relationNotAllowedClauses_ and _relationWhereClauses_ from private tot public before it started working. 
These two properties are not only used on $this model itself, but also on $relatedModel(s).
This problem also holds for a model's _primaryKey_, so for correct workings, if a primary key is explicitly defined in a model, it should be done so _public_-ly.
I'am using Laravel-Eloquent-Join version 2.0.0, so these issues might already have been solved in later version(s), not sure ...

**Comment by fico7489** [comment]
@ReneBakkerBBIT  do you want to submit PR?

**Comment by ReneBakkerBBIT** [comment]
No thanks, I suggest you change the two words (Private to Public) in a future version. No need to set up an extra branch for such a small issue ...

**Comment by fico7489** [comment]
@ReneBakkerBBIT  ok then, I will change this. The package has more reputation if more users had committed something event a typo fix...

**Comment by fico7489** [comment]
@ReneBakkerBBIT  I pushed changes, try now with newest 2.0.2. version.

PS. 2.0.* tags are or laravel 5.4.*

**Comment by fico7489** [comment]
@ReneBakkerBBIT  can you confirm that this is fixed ?

**Comment by ReneBakkerBBIT** [comment]
Yes, I have updated to version 2.0.2 and succesfully used the package afterwards ...

**Comment by fico7489** [comment]
great
