### ISSUE TITLE
Join not using localKey or ownerKey

### ISSUE THREAD

**Issue by Sharptsa** [fico7489/laravel-eloquent-join#41]
Loving this package but I'm having a small issue with it.

The joins are not performed on the localKey for HasOne/HasMany relations nor on the ownerKey for BelongsTo relations.

Example :
```
class Animal extends BaseModel
{
    public function legs()
    {
        return $this->hasMany(Leg::class,
            'animal_hash', 'hash');
    }
}

class Leg extends BaseModel
{
    public function animal()
    {
        return $this->belongsTo(Animal::class,
            'animal_hash', 'hash');
    }
}

dd(Animal::query()->joinRelations('legs')->toSql());
dd(Leg::query()->joinRelations('animal')->toSql());
```

This outputs : 

> "select animals.* from `animals` inner join `legs` on `legs`.`animal_hash` = `animals`.`id` group by `animals`.`id`"
"select legs.* from `legs` inner join `animals` on `animals`.`id` = `legs`.`animal_hash` group by `legs`.`id`"

When it should be :

>"select animals.* from `animals` inner join `legs` on `legs`.`animal_hash` = `animals`.`hash` group by `animals`.`id`"
"select legs.* from `legs` inner join `animals` on `animals`.`hash` = `legs`.`animal_hash` group by `legs`.`id`"

I'll try to do a PR but I'd like to have your thoughts on this.

**Comment by fico7489** [comment]
all done here : https://github.com/fico7489/laravel-eloquent-join/pull/42

**Comment by Sharptsa** [comment]
I guess I was not precise enough in my example. The issue is when you are trying to do a join on a column that is not the primary key.

To be more explicit, here's a new exemple using the test classes: 

```
<?php

namespace Fico7489\Laravel\EloquentJoin\Tests\Models\Key;

use Fico7489\Laravel\EloquentJoin\Tests\Models\BaseModel;

class Seller extends BaseModel
{
    protected $primaryKey = 'id';

    protected $table = 'key_sellers';

    protected $fillable = ['title', 'deleted_at'];

    public function location()
    {
        return $this->hasOne(Location::class, 'key_seller_id', 'key_id_seller');
    }

    public function locations()
    {
        return $this->hasMany(Location::class, 'key_seller_id', 'key_id_seller');
    }
}
```

```
<?php

namespace Fico7489\Laravel\EloquentJoin\Tests\Models\Key;

use Fico7489\Laravel\EloquentJoin\Tests\Models\BaseModel;

class Order extends BaseModel
{
    protected $primaryKey = 'id';

    protected $table = 'key_orders';

    protected $fillable = ['number', 'seller_id'];

    public function seller()
    {
        return $this->belongsTo(Seller::class, 'key_seller_id', 'key_id_order');
    }
}
```
```
        Schema::create('key_orders', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('key_id_order');
            $table->string('number')->nullable();
            $table->unsignedInteger('key_seller_id')->nullable();

            $table->foreign('key_seller_id')->references('id')->on('sellers');
        });

        Schema::create('key_sellers', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('key_id_seller');
            $table->string('title')->nullable();
            $table->unsignedInteger('city_id')->nullable();
        });
```
If you start phpunit with those changes, you'll see we still have the same problem as above.
It's the reason I was using `getOwnerKey()` and `getQualifiedParentKeyName()` in my PR which take the keys defined in the relation or fallback to the primary_key if not set.

**Comment by fico7489** [comment]
can you create a new PR now when we have tests  ?

**Comment by fico7489** [comment]
comment is added at PR ...

**Comment by Sharptsa** [comment]
This is now fixed, thanks for your reactivity !  :+1:
