### ISSUE TITLE
'Group by': overkill?

### ISSUE THREAD

**Issue by ReneBakkerBBIT** [fico7489/laravel-eloquent-join#5]
Philip,
I have been playing around a little with your package, but I think there is a fundamental issue expressed in the first example of your documentation (Posts joining Category); in particular the second problem (the 'group by Post.id'). If you join only one Category to a Post (because relation is HasOne), the second problem is clearly not there. However, if you would join more Categories to a Post (relations hasMany, etc.), indeed there is a problem/question as to decide on which of the multiple Categories the sort has to be perfomed.

Now, documentation clearly states that only hasOne and BelongsTo relations are supported. If this is so, there is no need to append a 'group by Post.id' to the generated SQL.
In fact this extra 'group by Post.id' addition is the reason why e.g. executing the query with '->count()' returns 1 (which is b.t.w. an identical result to using leftJoin in stead of whereJoin) .
Without this extra 'group by Post.id' addition, '->count()' would return the exact number of Posts selected.

I.m.h.o. you coud do without the 'group by' in the generated SQL. Love to hear your point of view ...

**Comment by fico7489** [comment]
1.Thanks for noticing that queries are not working well with count()
2.groupBy make sense with hasOne relation because this relation can have more rows and also I am planning to extend the plugin filter to all relations, not only hasOne and belongsTo.
3.I am looking for solution for count() problem, I see 3 solutions
-extend Builder
-create countJoin() method
-remove groupBy from query generator

I am closest to the second solution, but I still not 100% sure...

**Comment by ReneBakkerBBIT** [comment]
Glad to hear you ackowledged the count() issue. 

As for your second point: I don't agree that a hasOne() relation can have more rows. It can't. Is it possible that you are referring to the inverse relation of a hasOne() relation? That then, must be (see Laravel documentation on relationships) a BelongsTo() relation (not very realistic, sinds Post/Categorie would be a true 1:1 relation).

More realistically would be a 1:n relation From Categorie to Post, (or n:1 from Post to Category), which would be implemented as a Posts() method containing hasMany() on the Category model, and a Category() method containing  belongsTo() on the Post model. 

Only in the latter case there are more (Post model) rows involved. However, in both cases Category is on the 1-side of the relation, so that it wil not result in multiplication of Posts when joined. Hence: no orderBy() needed on the Post side when generating SQL. 

So for the solution to the count() issue, i.m.h.o. it would suffice to remove the generated orderBy(), and the package (in it's current state and versions at least) is in the clear.

For future versions that will include other relations, such as 1:n or m:n between model A and B, you will have to decide what a whereJoin() actually is going to perform: does it filter out the A model and if so: on what grounds (fields) from which B model rows?

A similar questions arises as for the orderByJoin() actions in such cases: if an A model row has multiple B model rows, which B model row field(s) is/are going to be used to sort on?

Interesting discussion ... :) ...

**Comment by fico7489** [comment]
**BelongsTo** does not need groupBy, **HasOne** need groupBy because if you have DB tables : 

```
sellers
id|name
1|test

locations
id|name|seller_id
1|test|1
2|test2|1

```
and Seller model

```
class Seller {
    public function location()
    {
        return $this->hasOne(Location::class);
    }
}
```

this code will give you 1 : 

`count(Seller::orderBy('name')->get()); //1
`

this code will give you 1 : 

`count(Seller::orderByJoin('location.name')->get()); //1 with group by`

this code will give you 2 : 

`
count(Seller::orderByJoin('location.name')->get()); //2 without group by`

maybe we will have fewer problems if we remove groupBy, but in that case, this plugin is limited to only this  4 relations: HasOne, BelongsTo, MorphTo and MorphOne...

I can add joinCount() which can generate this code : 

```
SELECT count(*) FROM (
    select sellers.* from sellers
        left join locations
        on locations.seller_id = sellers.id
        group by sellers.id) sellers;
```

and that would work, but it would be very confusing that count() and joinCount() give a different number, also paginator support has count() built inside and this is also a huge problem...

I will see this week what will decide...

**Comment by ReneBakkerBBIT** [comment]
Thanks for your example and explanation. 
However, your Sellar/Location example is NOT about a hasOne() relation from Sellers tot Locations, its about a hasMany() relation! The foreign key field seller_id in Locations contains value 1 twice, and for these database situations, you should code a Locations() method with a hasMany() relation at the Sellars side. Of coure you can code/use a hasOne() relation, but thats is just wrong modelling. Documentation only connects hasOne() (and it's reverse relation belongsTo()) to a 1:1 relation between model records and your example is simply not such a situation.
I'am sorry I sort of keep on nagging about this, but in fact it will make your package-development-life easier for at least these 1:1 relations, because you can really do without the OrderBy() clause for them.
As I said before: the problems (choices) will soon arrive when trying to implement the other types of relation ...

**Comment by fico7489** [comment]
@ReneBakkerBBIT yeah this is the theory, but I am working on a really big project(more than 10 developers) and we have : 

```
class Seller {
    public function locations()
    {
        return $this->hasMany(Location::class);
    }

    public function locationPrimary()
    {
        return $this->hasOne(Location::class)->where(['is_primary' => 1]);
    }
}
```

and for many reasons, more locations from the same seller have is_primary = 1  and this example proves my point...

:D

**Comment by ReneBakkerBBIT** [comment]
OK, I'am not going to argue (against 10+ people!) whether the implementation of locationPrimary() is correct or desirable (although I wonder which of the multiple Primairy Seller locations this method will actually return), but your point is taken. Usage of hasOne() does not garantee a true 1:1 relation in terms of database record existence, the relational clauses (hasOne(), hasMany()) appearently being just a different way to execute the queries. I found remarks along these lines elsewhere on the internet also.

So that leaves the orderBy() problem as-is, I guess ...

**Comment by fico7489** [comment]
I will see in next few days what I will decide, maybe I will remove groupBy

**Comment by imagine10255** [comment]
@fico7489 
I think if it will cause the same result,
That should be handled from the data structure or model.
Maybe it shouldn't be hasOne(), but hasMany(),

Unwanted situation feels increased loss to the database
groupBy() may be decided by the user or not

**Comment by fico7489** [comment]
this issue is for an older version of the package, closing ....
