### ISSUE TITLE
Order clause causing error

### ISSUE THREAD

**Issue by ionesculiviucristian** [fico7489/laravel-eloquent-join#50]
Hi. I'm getting an weird error and I don't know why:
```php
   Exception  : Property [relationClauses] does not exist on the Eloquent builder instance.

  at /var/www/html/projects/platforma/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1301
    1297|         if ($key === 'orWhere') {
    1298|             return new HigherOrderBuilderProxy($this, $key);
    1299|         }
    1300| 
  > 1301|         throw new Exception("Property [{$key}] does not exist on the Eloquent builder instance.");
    1302|     }
    1303| 
    1304|     /**
    1305|      * Dynamically handle calls into the query instance.

  Exception trace:

  1   Illuminate\Database\Eloquent\Builder::__get("relationClauses")
      /var/www/html/projects/platforma/vendor/fico7489/laravel-eloquent-join/src/Traits/JoinRelationTrait.php:17

  2   Fico7489\Laravel\EloquentJoin\Relations\HasManyJoin::__call("orderBy")
      /var/www/html/projects/platforma/app/CMS/Offers/Offer.php:115
```
Offer model uses EloquentJoin and has many selectablesPivots.
```php
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function selectablesPivots()
    {
        return $this->hasMany(OfferHasOfferSelectable::class, 'offer_id')->orderBy('order');
    }
```
And load them as follows
```php
        $baseOffers = Offer::with(['groups.optionsPivots.option', 'selectablesPivots.selectable'])
            ->where('is_template', 1)
            ->get();
```

**Comment by ionesculiviucristian** [comment]
Removing the ```php ->orderBy('order') ``` part "fixes" the problem. Somehow the trait, relations and  eloquent don't play well when using order clauses.

**Comment by ionesculiviucristian** [comment]
Also this line fails:
```php
$this->getQuery()->relationClauses[] = [$method => $parameters];
```
when running the code like this:
```php
$this->contract->educationUnits()->forceCreate([
                        'contract_id'         => $this->contract->getKey(),
                        'education_unit_type' => EducationUnitType::getType($educationUnit['type']),
                        'education_unit_id'   => (int) $educationUnit['id'],
                        'participants_count'  => (int) $educationUnit['participants_count'],
                    ]);
```
Contract model having the trait. Using save instead of forceCreate works.

**Comment by ionesculiviucristian** [comment]
Maybe something like this will fix it:
```php
        if ($this->getQuery() instanceof EloquentJoinBuilder) {
            $this->getQuery()->relationClauses[] = [$method => $parameters];
        }
```

**Comment by fico7489** [comment]
1. You said "Adding the trait to all relations solves the problem.", do you mean "Adding the trait to all models solves the problem." ?

2. I tried to run forceCreate() and everything works without errors, can you produce an error with my models in Test folder ?

**Comment by ionesculiviucristian** [comment]
1. I was referring to the models, yes.
2. Unfortunately I had to do manual joins and removed the library. I'll test it on a new branch.

**Comment by qooco** [comment]
Solution: 
EloquentJoinBuilder  107 line: $relatedKey = $relatedRelation->getForeignKey();

BelongsTo getForeignKey & getOwnerKey Methods

The **getForeignKey**, getQualifiedForeignKey, and getOwnerKey methods of the  BelongsTo relationship have been renamed to **getForeignKeyName**,  getQualifiedForeignKeyName, and getOwnerKeyName respectively, making the method names consistent with the other relationships offered by Laravel.

**Comment by fico7489** [comment]
@ionesculiviucristian  fixed here : https://github.com/fico7489/laravel-eloquent-join/commit/c8041812a82ae6f8983fa09096b2d4992409b9bb#diff-9c69b88803869495fd1ae525364041fd
