### ISSUE TITLE
Relation with withTrashed() break after laravel version 5.7.22

### ISSUE THREAD

**Issue by mungpara** [fico7489/laravel-eloquent-join#52]

**Comment by fico7489** [comment]
now I tried to run tests for laravel "v5.7.25" and everything works as expected without error, maybe you did not configured something properly ?

**Comment by mungpara** [comment]
have you tried with laravel v5.7.22

**Comment by mungpara** [comment]
Look at this
https://github.com/laravel/framework/issues/27357#issuecomment-458899452

**Comment by mungpara** [comment]
any update?
