### ISSUE TITLE
Property [relationClauses] does not exist on the Eloquent builder instance.

### ISSUE THREAD

**Issue by pryley** [fico7489/laravel-eloquent-join#54]
Similar to #50 I get an error after upgrading to Laravel 5.7.*

This is an extract of one of the Models:

```php
use Fico7489\Laravel\EloquentJoin\Traits\EloquentJoin;
use Illuminate\Database\Eloquent\Model as EloquentModel;

class Asset extends Model
{
    use EloquentJoin;

    public $timestamps = false;

    protected $casts = [
        'date' => 'datetime',
    ];

    public function latestCheckout()
    {
        return $this->hasOne(Checkout::class)->latest('date');
    }
}
```

Elsewhere:

```php
    Asset::orderByJoin('part.part_no', 'asc')
        ->orderBy('serial', 'desc')
        ->get()

    // and

    $remaining = Asset::whereIn('asset.id', $ids)
        ->whereJoin('part.part_no', '!=', static::EXCLUDE)
        ->get()
        ->map(function ($asset) {
            return $asset->in_stock;
        });
```

`app(Asset::class)->latestCheckout()` throws an Exception: "Property [relationClauses] does not exist on the Eloquent builder instance."

https://github.com/fico7489/laravel-eloquent-join/issues/50#issuecomment-460245717 seems to fix the problem. 

The issue happens because the `Checkout` class does not use the `EloquentJoin` trait, only the `Asset` class does. If I add the `EloquentJoin` trait to the `Checkout` class then the Exception is no longer triggered.

**Comment by fico7489** [comment]
already fixed
