### ISSUE TITLE
Consider change joinQuery as protected method

### ISSUE THREAD

**Issue by s207152** [fico7489/laravel-eloquent-join#59]
In my case, ```InvalidRelationGlobalScope``` is being thrown when I am using this package with Clockwork.

So I decided to extend the ```EloquentJoinBuilder``` to handle the Clockwork global scope and other custom global scopes built for my application.

However, looks like I have to rewrite the whole thing because both core functions ```performJoin``` and ```joinQuery``` are marked as private.

Is it better to change it to protected or create a protected method for us to override the global scope applying behaviour?

**Comment by calvinps** [comment]
Same issue with using Laravel Scout (when adding "Searchable" trait to model classes). In my case I tried commenting out the `throw new InvalidRelationGlobalScope();` and everything still works fine. 

Seems like this package needs to rethink allowing other global scopes that might get applied by other packages.

**Comment by fico7489** [comment]
I changed methods to protected https://github.com/fico7489/laravel-eloquent-join/commit/16d92b760e9c027880c2ae7d08e4a3a62f6a233b
