### ISSUE TITLE
Does not work when LaravelArdent installed

### ISSUE THREAD

**Issue by james-coder** [fico7489/laravel-eloquent-join#65]
Somehow, when I am using https://github.com/laravel-ardent/ardent and extending Ardent instead of Eloquent's "Model" (Ardent also extends Model, so I'd think maybe these could be used together? https://github.com/laravel-ardent/ardent/blob/14660469b9a39b46c0174cb2071ad21f40a988df/src/Ardent/Ardent.php#L25 ) none of the static methods are bound to the class.

Example:
User::joinRelations('emails')
"No such method joinRelations()"

Then I undo the LaravelArdent changes, extend Eloquent's Model instead of Ardent, and it works just as the documentation says.

I'm not sure if laravel-eloquent-join somehow does something very specific with Eloquent's Model to the point where using an extended class doesn't work. (But this is weird, because laravel-eloquent-join points out you can use a BaseModel extending Eloquent's Model, this is pretty much what LaravelArdent is doing.)

No error is seen in Laravel log, it just never adds the static methods like "joinRelations()".

**Comment by fico7489** [comment]
Is just general problem to combine more packages that both extends eloquent, it is possible but it requires a strong coding skills...
