### ISSUE TITLE
min and max doesn't work anymore with whereJoin

### ISSUE THREAD

**Issue by getriebesand** [fico7489/laravel-eloquent-join#66]
I have upgraded from v3 to v4 and my min and max querys doesn't work anymore.
If I use whereJoin and max() I don't get the max value. This is caused by a "group by" which will be added in v4 by whereJoin().

**Comment by fico7489** [comment]
v3 and v4 are not compatible, can you describe what are you trying to do and how ?

**Comment by getriebesand** [comment]
https://github.com/fico7489/laravel-eloquent-join/blob/master/src/EloquentJoinBuilder.php#L227

This groupby is new and its the reason that max() and min() doesn't work anymore. 

I want to make a query, where I get the highest year in the table, but only from records where a relation has a field with a given value.

Appointment::whereJoin('state.country.id', 81)->max('year');
in v3 I get the highest year. in v4 I get every row with the year because of that groupby.

I don't if I'm doing something wrong. At the moment I have forked this package and removed this groupby and all my querys working as expected.
