### ISSUE TITLE
Duplicate join using aliased tables

### ISSUE THREAD

**Issue by Sharptsa** [fico7489/laravel-eloquent-join#67]
Spotted an issue when doing joins with `$useTableAlias=true`

If you are doing multiple `where` on the same relation, it creates one join per where condition.
It's because when we check if the table has already been join, it's done on aliases (which are unique) instead of the table name.

Example: 

```
Order::setUseTableAlias(true)
       ->whereJoin('seller.id', '=', 1)
       ->whereJoin('seller.title', '=', 'shop')

select orders.*
from "orders"
         left join "sellers" as "5d542264d39e3" on "5d542264d39e3"."id" = "orders"."seller_id"
         left join "sellers" as "5d542264d3a11" on "5d542264d3a11"."id" = "orders"."seller_id"
where "5d542264d39e3"."id" = ?
  and "5d542264d3a11"."title" = ?
  and "orders"."deleted_at" is null
group by "orders"."id";
```

instead of 

```
select orders.*
from "orders"
         left join "sellers" as "5d542264d39e3" on "5d542264d39e3"."id" = "orders"."seller_id"
where "5d542264d39e3"."id" = ?
  and "5d542264d39e3"."title" = ?
  and "orders"."deleted_at" is null
group by "orders"."id";
```

I'll do a PR to fix this and add some tests.

**Comment by fico7489** [comment]
thanks for the catch and the PR, I just changes a one line : https://github.com/fico7489/laravel-eloquent-join/commit/456c9ba62658f2d969e259d57e354bfa26d46164

**Comment by Sharptsa** [comment]
Yeah, right... using a hash function for the alias works too. :smile:
