### ISSUE TITLE
Add global scope support or allow withoutGlobalScopes() in relations

### ISSUE THREAD

**Issue by NesCafe62** [fico7489/laravel-eloquent-join#69]
Hi, I have an error:
"Package allows only SoftDeletingScope global scope."

I don't need soft deleting. My model has global scope
```
static::addGlobalScope( function($query) {
    $query->where('isEntering', false);
});
```
Without it all works fine, but I want it to remain.
I tried to add `withoutGlobalScopes()` to relation, but it shows another error:
"Package allows only following clauses on relation : where, orWhere, withTrashed, onlyTrashed and withoutTrashed."

I watched the sources. Is seems `withoutGlobalScopes()` doesn't remove `$relationBuilder->scopes` (maybe) but adds `$relationBuilder->relationClauses` with `$method = 'withoutGloalScopes'`... and it is not supported (as second error says).

**Comment by NesCafe62** [comment]
Temporary fixed by adding to `applyClauseOnRelation` in my fork
```
} elseif ($method === 'withoutGlobalScopes') {
            //do nothing
```

**Comment by fico7489** [comment]
Laravel is very flexible so it is really hard to support all those options like global scopes. I just put constraint that you can't use global scopes if you want to use this package, from my side this behavior that you described is perfectly normal, you can't combine global scopes if you want to use this package....Of course it would be nice that your case is resolved, feel free to submit a PR with the test....

**Comment by zawadsoon** [comment]
@fico7489 
I know this is quite old topic. But it's not clear for me... 

Why using this package we are unable to define global socpes, what are caveats, what is motivations for that, what am I missing? 

Would you be so kind to help me understand or at least point me where can I get knowledge?
