### ISSUE TITLE
QueryException - Name DB?

### ISSUE THREAD

**Issue by joserick** [fico7489/laravel-eloquent-join#7]
"SQLSTATE[42000]: Syntax error or access violation: 1055 'crm_db.cities.name' isn't in GROUP BY..."

Hi,
I check your repository in local and work perfectly but upload to server with same DB, and I get a error "1055 '**crm_db**.cities.name'" where appear name of database as if it were the name of table and of course mysql don't find the column.

Could you tell me where you print the name of the table? and I try to delete the name of the database directly.

Thank you

**Comment by fico7489** [comment]
I need more info if you want me to help you.

1. can you provide generated query at local and at the server?
2. can you provide table names with attributes on which you are performing query?

**Comment by joserick** [comment]
Hi,
thanks for answering, I found how to solve it, you have to change in 'config/database.php' the 'strict' to 'false'.

I did not understand very well about the 'strict' but it work.

`'mysql' => [`
`------'strict' => false,`
`]`

regards and thank you for believing so amazing repository.

**Comment by fico7489** [comment]
@joserick  thanks, I am glad that works. 
I will add this to readme in next documentation update iteration.
