### ISSUE TITLE
Why do I need to disable MySQL strict mode?

### ISSUE THREAD

**Issue by PatBriPerso** [fico7489/laravel-eloquent-join#70]
I read that I need to set `'strict' => false` for my MySQL connection to have your package work.
I would prefer to keep strict mode enable so I made a quick test:
- clone your package
- change your setting in TestCase.php to have `'strict' => true`
- change ServiceProvider.php to test against MySQL : `$_ENV['type'] = 'mysql';`
- launch phpunit

and there is no error reporting by phpunit: all your tests passed (58).

So why do I need to disable strict mode?
In which case is it mandatory?

Please explain.

Regards,
Patrick

**Comment by fico7489** [comment]
'strict' => false is from an older version of the package I change it to true now, thanks for the feedback....
