### ISSUE TITLE
Question: withRelations not joining related models

### ISSUE THREAD

**Issue by georanma** [fico7489/laravel-eloquent-join#75]
Having some issues with the basic `joinRelations` statement. I have eloquent models defined, and the relationship is a one to one, but the results dont include the relationship. 

Laravel Version: 6.9
Laravel Eloquent Join: 4.0.9

**Lender Model**
`use Fico7489\Laravel\EloquentJoin\Traits\EloquentJoin;
use Illuminate\Database\Eloquent\Model;

class Lender extends Model
{
    use EloquentJoin;

    /**
     * Get the details associated with a lender
     */
    public function details()
    {
        return $this->hasOne(LenderDetail::class);
    }

    /**
     * Get the address associated with a lender
     */
    public function address()
    {
        return $this->hasOne('App\LenderAddress');
    }

    /**
     * Get the details associated with a lender
     */
    public function zipCodes()
    {
        return $this->belongsToMany('App\ZipCode', 'lender_zip_codes');
    }
}
`

**LenderDetail Model**
`
use Illuminate\Database\Eloquent\Model;

class LenderDetail extends Model
{
    /**
     * Get the lender associated with a details
     */
    public function lender()
    {
        return $this->hasOne('App\Lender');
    }

}
`

**Query**
`Lender::joinRelationship('details')->get()`

**Results**
`Illuminate\Database\Eloquent\Collection {#3016
     all: [
       App\Lender {#3020
         id: 1,
         created_at: null,
         updated_at: null,
         lender: "FIRST COMMONWEALTH FCU",
         bureau_data: "Verbal - EX",
         experian: 1,
         equifax: 1,
         transunion: 0,
         nation_wide: 1,
         infusionsoft_id: 620939,
         primary_lender: 1,
       },
     ],
   }
`
**Lender::withRelations('details')**
` Fico7489\Laravel\EloquentJoin\EloquentJoinBuilder {#3011
     +baseBuilder: null,
     +relationClauses: [],
   }
`
Happy to provide anything else to debug

**Comment by fico7489** [comment]
what are you trying to achieve ? 
"details" are joined in your query, but the attributes are not in the selected.

you can apply clauses and sorts on joined relationships, but they are  not in the select clause :

```
Lender::joinRelationship('details')
->where(['details.id' => 1])
->get()
```

**Comment by georanma** [comment]
@fico7489 I think i ended up just refactoring my frontend to account for the change in data structure, and moved away from the package. Thanks for getting back to me and providing this option.
