### ISSUE TITLE
Syntax error or access violation: 1055 '...' isn't in GROUP BY

### ISSUE THREAD

**Issue by rcreate** [fico7489/laravel-eloquent-join#79]
When I try to do this:
`SourceLogRun::joinRelations('logSourceObject')
     ->find($runId)`

The mysql error (MariaDB) is thrown. The reason is that a group by is added to the statement but the select clause is selecting more columns. For this simple query there's no need to group by something.

The following line should be refactored to count($relations) > 2 because of the concatenation '.FAKE_FIELD' above or the group by should not be done by default.
https://github.com/fico7489/laravel-eloquent-join/blob/c2f5cac2f316f7b54c96d8038b29359e9b88429c/src/EloquentJoinBuilder.php#L224

**Comment by fico7489** [comment]
group by is required for HasOne and HasMany because without it query can join more that one item and duplicated rows can appear in results
