### ISSUE TITLE
Question: Eager loading

### ISSUE THREAD

**Issue by half2me** [fico7489/laravel-eloquent-join#87]
How would I eager load using JOINs? [Eager Loding](https://laravel.com/docs/6.x/eloquent-relationships#eager-loading)

For example if I wanted this:
```php
$books = App\Book::with(['author', 'publisher'])->get();
```
How would I achieve the same but with JOIN queries?

**Comment by fico7489** [comment]
eager loading from eloquent should work as expected

**Comment by half2me** [comment]
@fico7489 I think you are missing my question. Eager loading works fine, but doesn't use JOINs. Is there a way to use JOINs for eager loading?

**Comment by fico7489** [comment]
Oh, you are asking that, currently this package does not support that, but it is possible to implement that for HasOne and BelongsTo relations, but not for HasMany

**Comment by half2me** [comment]
@fico7489 thanks for the reply. I've heard that being said before, that it can't be done for `HasMany`. What is the reason for this? I've used CakePHP a lot in the past, and their ORM has support for joining `HasMany` relations.

**Comment by fico7489** [comment]
join table and eager load is not the same, a cakephp is probably doing the "eager load" in your case....
