### ISSUE TITLE
[Suggestion] Support Oracle Eloquent Driver

### ISSUE THREAD

**Issue by ADRDev** [fico7489/laravel-eloquent-join#9]
I think the only thing preventing it from working is that the relationship between SELECT and GROUP BY works differently in Oracle.

``
 $builder->select($baseTable . '.*')->groupBy($baseTable . '.' . $baseModel->primaryKey);
``

This won't work. Oracle will error because the list of columns selected is different than the list of columns grouped by.

Some info:
https://stackoverflow.com/questions/25782524/select-group-by-in-oracle

For reference:
https://yajrabox.com/docs/laravel-oci8/master/oracle-eloquent

**Comment by fico7489** [comment]
groupBy() will be removed in next package version...
